### ISSUE TITLE
文档不完善

### ISSUE THREAD

**Issue by yibuyisheng** [darukjs/daruk#100]
按照文档鼓捣了下，被[配置](https://darukjs.com/tutorial/darukconfig.html#%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)卡住了，不知道什么含义，无法进行下一步。

能否完善一下文档。

**Comment by yibuyisheng** [comment]
结合日志来看，koa-bodyparser 应该是被初始化进去了的：
![image](https://user-images.githubusercontent.com/2581682/77179884-1b488480-6b04-11ea-8ed7-29526ce881cd.png)

但是在使用 POST 请求接口的时候（带了 form-data 格式的参数），拿到的 `this.ctx.body` 是 `undefined`，如果真的 bodyparser 生效了，拿到的应该是请求 body 中的参数。不知道是不是什么地方配置了规则对接口啥的进行了过滤，结合文档和代码，一脸懵逼：
![image](https://user-images.githubusercontent.com/2581682/77180346-bd686c80-6b04-11ea-862a-1f369e2a152d.png)

**Comment by Youjingyu** [comment]
@yibuyisheng ctx.request.body

**Comment by yibuyisheng** [comment]
@Youjingyu 非常感谢，期待文档完善。

**Comment by xiaojue** [comment]
嗯 1.0文档比较老了 2.0已经写完了 但是还没有发release，尽快吧…😭

**Comment by xiaojue** [comment]
update readme for 2.x

**Comment by ghost** [comment]
> @yibuyisheng ctx.request.body

ohhhhhhh

**Comment by ghost** [comment]
> 嗯 1.0文档比较老了 2.0已经写完了 但是还没有发release，尽快吧…😭

daruk 真香
