### ISSUE TITLE
建议更换koa-router为@koa/router

### ISSUE THREAD

**Issue by yumindeckard** [darukjs/daruk#101]
**Describe the bug**

**koa-router is `NOT` actively maintained. It may have bugs.
`@koa/router` is a fork of it and has the same APIs. And it's developed by the official Koa team.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yumindeckard** [comment]
其实就是一行代码的事，API都一样，什么都不用改，把import改了就行

**Comment by xiaojue** [comment]
可以，考虑下。

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/eb2b5ae11e0f905642b54a280e25cccefbf52811
