### ISSUE TITLE
@types/node 导致编译失败

### ISSUE THREAD

**Issue by chuyik** [darukjs/daruk#113]
`daruk` 存在两个不同的 `@types/node` 版本，可能导致 `tsc` 编译命令失败。
- `daruk`: "@types/node" "^10.12.18"
- `daruk-exit-hook`: "@types/node" "^12.0.0"

**错误报告**
```js
node_modules/daruk/types/core/daruk.d.ts:1:23 - error TS4090: 
Conflicting definitions for 'node' found at 'node_modules/daruk/node_modules/@types/node/index.d.ts' 
and 'node_modules/@types/node/index.d.ts'. 
Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
Found 1 error.
```

**处理方法**
`daruk` 和 `daruk-exit-hook` 的 `package.json` 中的 `@types/*` 依赖应该挪动到 `devDependencies`。

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/06ad3b81a3b97cb2f27bf10a20725fbfab5be868
https://github.com/darukjs/daruk-exit-hook/commit/a53ccccb0bb6048bd8d57d198a9341feb21609a8

done
