### ISSUE TITLE
controller 装饰器的参数类型声明漏咯

### ISSUE THREAD

**Issue by ghost** [darukjs/daruk#118]
问题
![image](https://user-images.githubusercontent.com/72804427/102570399-36dbcc80-4122-11eb-8d40-132c57d5f72f.png)

源码
![image](https://user-images.githubusercontent.com/72804427/102570426-46f3ac00-4122-11eb-8261-3ec24ec980ce.png)

**Comment by xiaojue** [comment]
@changnan666 你的 daruk 版本是多少？

**Comment by changnan666** [comment]
> @changnan666 你的 daruk 版本是多少？

2.2.3

**Comment by ghost** [comment]
@xiaojue 2.2.3

**Comment by xiaojue** [comment]
@changnan666 2.2.4 修复了，types 目录下的 d.ts 之前没有自动跟着更新，改了一下 我本地测试 ok 了。

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/17a2fa63ca1f8ebb782249362355d6054ec948f3

**Comment by ghost** [comment]
么么哒
