### ISSUE TITLE
缺少染色功能的文档描述

### ISSUE THREAD

**Issue by chuyik** [darukjs/daruk#120]
README 中提及`自定义(性能日志 & 业务日志) 染色功能`，但文档没有对该特性进行描述。

请问下这个功能是有的吗，如何做染色呢？

**Comment by xiaojue** [comment]
如果你有多个使用 daruk 开发的 web 应用，互相有 api 调用的情况下，我们的 request 头里提供了染色的 id，利用的是https://github.com/darukjs/daruk-request-id 这个包，通过 ctx.request.id 来获取染色 id，然后去关联自己的日志，目前 daruk 还没有提供 rpc 或者request 相关的功能，需要自己在请求其他服务时带着这个 request.id 就可以实现染色啦。

后期有时间我会提供一些简单的 rpc 插件来默认支持，目前还需要自己做点工作。

性能日志的话可以参考这里的文档 ： https://darukjs.com/ecological/performance.html#%E4%B8%AD%E9%97%B4%E4%BB%B6%E6%80%A7%E8%83%BD%E8%AE%A1%E7%AE%97
