### ISSUE TITLE
文件既然已经确定了，直接 require 性能应该会更好

### ISSUE THREAD

**Issue by zhangwinning** [darukjs/daruk#126]
https://github.com/darukjs/daruk/blob/59b8110646c2d2d2708581aa32b10cb815c0a981/src/core/daruk.ts#L62

**Comment by xiaojue** [comment]
为了避免有意外的文件混入文件夹，loadFile 本身做了遍历和过滤，最后的实现就是 require，启动性能来说，还是保持代码简洁好一点。
