### ISSUE TITLE
Module 'v8-profiler-node8' can not install on Windows

### ISSUE THREAD

**Issue by Himself65** [darukjs/daruk#50]
**To Reproduce**
1. use a windows PC
2. clone this repo
3. run `npm install` or `yarn install`

**Comment by xiaojue** [comment]
https://www.luogu.org/paste/llum05p9

**Comment by hyj1991** [comment]
Please use VS2017 to build this module.

```bash
npm install --global --production windows-build-tools
npm install -g node-gyp
npm install v8-profiler-node8 --msvs_version=2017
```

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/cac8747bf78beaae1e4d1c1823aefaa4ca6f1222

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk-monitor-middleware
@Himself65  v0.5.7 release @myluluy
