### ISSUE TITLE
[Feature] built in ctx.request.body middleware in Daruk

### ISSUE THREAD

**Issue by xiaojue** [darukjs/daruk#61]
`ctx.request.body` will built in the framework

**Comment by Himself65** [comment]
what’s this meaning for?

**Comment by xiaojue** [comment]
@Himself65 support ctx.request.body~

update!

**Comment by Himself65** [comment]
why don’t use `koa-bodyparser`?

―― by Himself65 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: xiaojue <notifications@github.com>
发送时间: Thursday, May 16, 2019 4:30:36 PM
收件人: darukjs/daruk
抄送: 扩散性百万甜面包; Mention
主题: Re: [darukjs/daruk] [Feature] built in ctx.request.body middleware in Daruk (#61)


@Himself65<https://github.com/Himself65> support ctx.request.body~

update!

―

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/008029a55916f7720bf7c7a385223e26d153696e

use `koa-body` and add  daruk options `bodyOptions`
