### ISSUE TITLE
[Question] Is there any other elegant way to control router？

### ISSUE THREAD

**Issue by Chersquwn** [darukjs/daruk#78]
In the docs, i find that the controllers are routers. Daruk will recursively read the files in the controllers directory, using the file name as the routing path.

If i want to deprecate or temporarily deprecate some routers, i must delete the routes in the corresponding controllers, even the whole controllers.

Is there any other elegant way to control routers or controller？Such as an ignore file,  exclude flag or any other way.

**Comment by Himself65** [comment]
hmmm, add a new decorator like `@remove()` to remove the route?

**Comment by xiaojue** [comment]
we can add `@disabled()` decorator for controller class or method?

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/issues/79

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/issues/79
