### ISSUE TITLE
希望能完善一下文档

### ISSUE THREAD

**Issue by GaryChangCN** [darukjs/daruk#85]
**Is your feature request related to a problem? Please describe.**
按着默认配置是没法有上传文件的。

**Describe the solution you'd like**
需要在配置中加入 multipart true 才能开启

**Describe alternatives you've considered**
如果文档有说明就好了

**Additional context**

**Comment by imakan** [comment]
因为daruk内置了koa-body，我们只需要配置相应的信息，这个配置需要在`daruk.init.ts`中，配置`bodyOptions`选项,
```javascript
bodyOptions:{
    multipart: true
  }
```
稍后我们会补上文档
