### ISSUE TITLE
Enable strict type-checking

### ISSUE THREAD

**Issue by xiaoxiangmoe** [darukjs/daruk#99]
https://github.com/darukjs/daruk/blob/18daab03d1cc0abdf6f526c8d93bd38ab4e6d4ce/tsconfig.json#L25

Please  enable all strict type-checking options.

**Comment by himself65** [comment]
Not now, xiaojue haven’t done all the features

**Comment by xiaojue** [comment]
delay and need discussion

**Comment by xiaojue** [comment]
https://github.com/darukjs/daruk/commit/8fbd7f31258d3a3d33120859109a8ea0cbdfbb4c
